Vagrant.configure("2") do |config|
    config.vm.define "nginx" do |nginx|
      nginx.vm.box = "ubuntu/trusty64"
      nginx.vm.hostname = 'nginx'
      nginx.vm.network :private_network, ip: "10.10.10.100"
      nginx.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
      end
    end
    config.vm.define "web1" do |web1|
      web1.vm.box = "ubuntu/trusty64"
      web1.vm.hostname = 'web1'
      web1.vm.network :private_network, ip: "10.10.10.120"
      web1.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
      end
    end
    config.vm.define "web2" do |web2|
        web2.vm.box = "ubuntu/trusty64"
        web2.vm.hostname = 'web2'
        web2.vm.network :private_network, ip: "10.10.10.130"
        web2.vm.provider :virtualbox do |v|
          v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          v.customize ["modifyvm", :id, "--memory", 512]
        end
      end
  end

  